n_back:
  type: n_back
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - leftCamA
  - rightCamA
naturalistic_speech:
  type: naturalistic_speech
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - leftCamA
  - rightCamA
  - leftCamB
  - rightCamB
motor_task_finger_taps:
  type: motor_task_finger_taps
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - leftCamA
  - rightCamA
diadochokinesis:
  type: diadochokinesis
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - leftCamA
  - rightCamA
verbal_fluency:
  type: verbal_fluency
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - leftCamA
  - rightCamA
vowel_space:
  type: vowel_space
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - leftCamA
  - rightCamA
reach_grasp:
  type: reach_grasp
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Grasp Button
  - Microphone 1
  - Microphone 2
  - Force Sensor X
  - Force Sensor Y
  - Force Sensor Z
  - Barcode
  - leftCamA
  - rightCamA
  - leftCamB
  - rightCamB
tone_taps_closed:
  type: tone_taps_closed
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - leftCamA
  - rightCamA
sara:
  type: sara
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - leftCamA
  - rightCamA